apiVersion: apps/v1
kind: Deployment
metadata:
  name: drifting-desk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drifting-desk
  template:
    metadata:
      labels:
        app: drifting-desk
    spec:
      containers:
      - name: drifting-desk
        image: adinder/drifting-desk:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            value: "kafka-service:9092"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
