apiVersion: v1
kind: Service
metadata:
  name: drifting-desk-service
spec:
  selector:
    app: drifting-desk
  ports:
    - name: http        # Add a name for the port
      protocol: TCP
      port: 80       # Changed from 8080 to 8081
      targetPort: 8080 # Changed to match the new port
  type: ClusterIP